### ISSUE TITLE
Enable master branch as gh-pages?

### ISSUE THREAD

**Issue by sfsheath** [isaw-ga-3024/fall-2017#7]
Do we want to do this? Will let browsers display rendered version directly, which could be fun? (Also, demoing issue tracker...) -S.

**Comment by diyclassics** [comment]
I went back and forth on it and decided that I may have already introduced too many new features. That said, I did update the Doc to show how to simulate this functionality by prepending "https://htmlpreview.github.io/?" to their repo URLs.

**Comment by diyclassics** [comment]
If demand is there btw, I would happily host—and will likely bring up the idea for—a workshop outside of class time along the lines of "Creating an Academic CV/Portfolio with GH Pages and Jekyll" vel sim.

**Comment by diyclassics** [comment]
BTW It looks like I *will* run the Jekyll/CV workshop later this semester, for both our students (though outside of class) and anyone else in the ISAW community who is interested. I'll put off introducing this until then.
